const products = [
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/analog.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'2',
        name: 'Instax Camera',
        image:'/products/instax-b.jpg',
        description:'lorem ipsum dolor',
        brand:'Instax',
        category:'Electronics',
        price:'70$',
    },
    {
        id:'3',
        name: 'Analogue Camera',
        image:'/products/instax-g.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/instax-w.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/instax-y.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/instax.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/jupiter.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/kiev.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/kodak.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/lens.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/lens2.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/olympus.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    },
    {
        id:'1',
        name: 'Analogue Camera',
        image:'/products/pentax.jpg',
        description:'lorem ipsum dolor',
        brand:'Kiev',
        category:'Electronics',
        price:'80$',
    }



]
export default products;